parameters:
    esendex.authentication.class: Esendex\Authentication\LoginAuthentication
    esendex.dispatcher.class: Esendex\DispatchService

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  msg.sms.esendex.authentication:
    class: '%esendex.authentication.class%'
    arguments:
      - '%esendex.account_reference%'
      - '%esendex.username%'
      - '%esendex.password%'

  msg.sms.esendex.dispatcher:
    class: '%esendex.dispatcher.class%'

  msg.sms.esendex:
    class: Headsnet\EsendexSmsBundle\DependencyInjection\SmsSender\EsendexSdkService
    arguments:
      $virtualMobileNumber: '%esendex.vmn%'
